name: Lucio Villa
description: "Web Developer, Photographer, Latino"
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 3
baseurl: /luciovilla
domain_name: 'http://luciovilla.github.io/luciovilla'
google_analytics: 'UA-63525175-1'

# Details for the RSS feed generator
url:            'http://luciovilla.github.io/luciovilla'
author:         'Lucio Villa'
