name: Lucio Villa
description: "Web Developer & Photographer"
meta_description: "Portfolio and blog site for Lucio Villa."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 3
baseurl:
domain_name: 'http://luciovilla.com'
google_analytics: 'UA-63525175-1'

# Details for the RSS feed generator
url:            'http://luciovilla.com'
author:         'Lucio Villa'
